# Generated by Django 5.0.3 on 2024-03-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudents',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
