# Generated by Django 5.0.3 on 2024-04-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_students_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='password',
            field=models.CharField(default=1234, max_length=30),
            preserve_default=False,
        ),
    ]
