# Generated by Django 5.0.3 on 2024-04-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_students_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.TextField(),
        ),
    ]
